const mongoose = require("mongoose");
const express = require("express");
const app = express();
var cors = require("cors");
app.use(cors());

let port = process.env.port || 5001

let data = {
  goods: [
    {
      id: 1,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 2,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "Лидер продаж",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 3,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "Лучшая цена",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 4,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "Лидер продаж",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 5,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 6,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "Лучшая цена",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 7,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 8,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "Привезем сегодня",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 9,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 10,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "Лучшая цена",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 11,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 12,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "Лидер продаж",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 13,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 14,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "Привезем сегодня",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 15,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 16,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "Лучшая цена",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 17,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 18,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "Лидер продаж",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 19,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: " Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "мм: 250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
    {
      id: 20,
      title: "Кирпич облицовочный M95 Воткинский",
      price: 4500,
      status: "Привезем сегодня",
      photo: "../../../../img/goods/1.png",
      info: "Колво на поддоне, шт.  297  Формат одинарный",
      remainder: 10000,
      category: "Кирпич",
      catalog: "Стеновые материалы",
      manufacturer: "Багдановичское ОАО “Огнеупоры”",
      brand: "M2039",
      size: "250*120*65",
      weight: "5.8",
      watersupply: "9.8",
      frostresistant: "35",
      consumption: "26",
      quantitypallet: "224",
      quantitycar: "4032",
      color: "Красный",
    },
  ],

  categories: [
    "Стеновые материалы",
    "Фасадные материалы",
    "Строительные блоки",
    "Отделочные материалы",
    "Сухие смеси",
    "Благоустройство",
    "Лако-красочные материалы",
    "Прочие услуги",
    "Распродажа товаров",
  ],
};

let items = data.goods.map((item, index) => {
  if (item.status) {
    return item;
  }
});

function getItem(id) {
  let items = data.goods.filter((item, index) => {
    if (item.id == id) {
      return item;
    }
  });
  console.log(items);
  return items
}

app.get("/home", (req, res) => {
  res.send(items);
});

app.get("/home/categories", (req, res) => {
  res.send(data.categories);
});

app.get("/home/goods", (req, res) => {
  res.send(data.goods);
});

app.get("/home/goods/:id", (req, res) => {
  // console.log(getItem(req.params.id));
  res.send(getItem(req.params.id));
});

app.listen(port, () => {
  console.log(`${port} eshitishni boshladim`);
});
